// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quiz_web.Server.Data;

#nullable disable

namespace quiz_web.Server.Migrations
{
    [DbContext(typeof(QuizDBContext))]
    [Migration("20250113183442_PopulateTablesv2")]
    partial class PopulateTablesv2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("quiz_web.Server.Models.HighScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("HighScores");
                });

            modelBuilder.Entity("quiz_web.Server.Models.QuizAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("QuizAnswers")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("isCorrect")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("QuizAnswers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuizAnswers = "Stormwind",
                            QuizQuestionId = 1,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 2,
                            QuizAnswers = "Lordaeron",
                            QuizQuestionId = 1,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 3,
                            QuizAnswers = "Gilneas",
                            QuizQuestionId = 1,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 4,
                            QuizAnswers = "Quel'Thalas",
                            QuizQuestionId = 1,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 5,
                            QuizAnswers = "Zul'Gurub",
                            QuizQuestionId = 2,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 6,
                            QuizAnswers = "Icecrown Citadel",
                            QuizQuestionId = 2,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 7,
                            QuizAnswers = "The Nighthold",
                            QuizQuestionId = 2,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 8,
                            QuizAnswers = "Chambers of Xeric",
                            QuizQuestionId = 2,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 9,
                            QuizAnswers = "Gnomeregan",
                            QuizQuestionId = 3,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 10,
                            QuizAnswers = "Blackrock Spire",
                            QuizQuestionId = 3,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 11,
                            QuizAnswers = "Blackrock Depths",
                            QuizQuestionId = 3,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 12,
                            QuizAnswers = "The Black Morass",
                            QuizQuestionId = 3,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 13,
                            QuizAnswers = "Garrosh Hellscream",
                            QuizQuestionId = 4,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 14,
                            QuizAnswers = "Sylvannas Windrunner",
                            QuizQuestionId = 4,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 15,
                            QuizAnswers = "Vol'jin",
                            QuizQuestionId = 4,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 16,
                            QuizAnswers = "None of the above",
                            QuizQuestionId = 4,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 17,
                            QuizAnswers = "Stormwind",
                            QuizQuestionId = 5,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 18,
                            QuizAnswers = "Scarlet Monestary",
                            QuizQuestionId = 6,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 19,
                            QuizAnswers = "Stranglethorn Vale",
                            QuizQuestionId = 7,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 20,
                            QuizAnswers = "Durotar",
                            QuizQuestionId = 7,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 21,
                            QuizAnswers = "Tanaris",
                            QuizQuestionId = 7,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 22,
                            QuizAnswers = "Sholazar Basin",
                            QuizQuestionId = 7,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 23,
                            QuizAnswers = "Thane Korth'azz",
                            QuizQuestionId = 8,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 24,
                            QuizAnswers = "Lady Blaumeux",
                            QuizQuestionId = 8,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 25,
                            QuizAnswers = "Baron Rivendare",
                            QuizQuestionId = 8,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 26,
                            QuizAnswers = "Sir Zeliek",
                            QuizQuestionId = 8,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 27,
                            QuizAnswers = "Mining",
                            QuizQuestionId = 9,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 28,
                            QuizAnswers = "Blacksmithing",
                            QuizQuestionId = 9,
                            isCorrect = false
                        },
                        new
                        {
                            Id = 29,
                            QuizAnswers = "First Aid",
                            QuizQuestionId = 9,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 30,
                            QuizAnswers = "Fishing",
                            QuizQuestionId = 9,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 31,
                            QuizAnswers = "Shade of Akama",
                            QuizQuestionId = 10,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 32,
                            QuizAnswers = "Reliquary of Souls",
                            QuizQuestionId = 10,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 33,
                            QuizAnswers = "Illidan Stormrage",
                            QuizQuestionId = 10,
                            isCorrect = true
                        },
                        new
                        {
                            Id = 34,
                            QuizAnswers = "Mother Shahraz",
                            QuizQuestionId = 10,
                            isCorrect = true
                        });
                });

            modelBuilder.Entity("quiz_web.Server.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuizQuestion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionText = "Arthas Menethil was the prince of which kingdom in World of Warcraft?",
                            QuestionType = "radio-button"
                        },
                        new
                        {
                            Id = 2,
                            QuestionText = "Which raid instance is located in Stranglethorn Vale in World of Warcraft?",
                            QuestionType = "radio-button"
                        },
                        new
                        {
                            Id = 3,
                            QuestionText = "The entrance to Blackwing Lair raid is found inside what instance in World of Warcraft?",
                            QuestionType = "radio-button"
                        },
                        new
                        {
                            Id = 4,
                            QuestionText = "Who is the current Warchief of the Horde?",
                            QuestionType = "radio-button"
                        },
                        new
                        {
                            Id = 5,
                            QuestionText = "What is the name of the human capital city in World of Warcraft?",
                            QuestionType = "text"
                        },
                        new
                        {
                            Id = 6,
                            QuestionText = "Which four-wing instance located in Tirisfal Glades is frequently farmed by players in World of Warcraft?",
                            QuestionType = "text"
                        },
                        new
                        {
                            Id = 7,
                            QuestionText = "In which of these zones can you find the dwarwen hunter Hemet Nesigwary?",
                            QuestionType = "checkbox"
                        },
                        new
                        {
                            Id = 8,
                            QuestionText = "Which of these are the original Four Horsemen found in Naxxramas?",
                            QuestionType = "checkbox"
                        },
                        new
                        {
                            Id = 9,
                            QuestionText = "Which of these professions are of the secondary type?",
                            QuestionType = "checkbox"
                        },
                        new
                        {
                            Id = 10,
                            QuestionText = "Which of these bosses can you find in the raid Black Temple?",
                            QuestionType = "checkbox"
                        });
                });

            modelBuilder.Entity("quiz_web.Server.Models.QuizAnswer", b =>
                {
                    b.HasOne("quiz_web.Server.Models.QuizQuestion", "QuizQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("quiz_web.Server.Models.QuizQuestion", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
